# Generated by Django 5.1 on 2024-08-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regandlogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='Cpassword',
            new_name='cpassword',
        ),
    ]
